# Generated by Django 4.2.12 on 2024-10-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
